[build]
  base = "client"  # Directory where Netlify should look for the build files
  publish = "client/dist"  # Directory where the build files will be output
  command = "npm run build"  # Command to run the build script
