[build]
  command = "npm run build"  # Adjust this command based on your build setup
  publish = "build"          # Adjust this based on your build output directory

[context.production.environment]
  NODE_ENV = "production"
