services:
  - type: web
    name: googlebooks-app
    env: node
    plan: free
    buildCommand: cd client && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: your-database-name
          property: connectionString